# Generated by Django 4.0.5 on 2022-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_created_shopcart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
